skip_tags: true

version: 2.0.{build}

image: 
  - Visual Studio 2019
  - Ubuntu

environment:
  github_access_token:
    secure: EMJUnvkJwGXaFnohUmpxqyNd0R4hpMCeUtl5aVtHqFerhd0UdYc+lTJV3H3sIhg6
  github_email:
    secure: B5VQnP9LQP9stxxvu2G/3MCKhVySoSVf/mvyqHY5K8M=

init:
  - git config --global core.autocrlf input

build_script:
  - mkdir Artifacts/Release
  - dotnet tool restore
  - Nake.bat AppVeyorJobId=%APPVEYOR_JOB_ID% pack

test: off

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  artifacts:
    - path: Artifacts/Release/*.nupkg
